// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIJ60xYzbnWRDSUzJs4VDxzxR35y098E',
    appId: '1:302820889013:web:32cfb165fb2e5d051649fc',
    messagingSenderId: '302820889013',
    projectId: 'academicperformancecalculator',
    authDomain: 'academicperformancecalculator.firebaseapp.com',
    storageBucket: 'academicperformancecalculator.appspot.com',
    measurementId: 'G-W8P25DFHQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98NqGsTPGDePsgeZG2GxvlJrSthxUMZM',
    appId: '1:302820889013:android:5c2df6cb166370d91649fc',
    messagingSenderId: '302820889013',
    projectId: 'academicperformancecalculator',
    storageBucket: 'academicperformancecalculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWKkDn4QoVJpiwl8SKmOf4HwB2j3_uoZg',
    appId: '1:302820889013:ios:9edaad31488e54831649fc',
    messagingSenderId: '302820889013',
    projectId: 'academicperformancecalculator',
    storageBucket: 'academicperformancecalculator.appspot.com',
    iosClientId: '302820889013-bas0k8pdqqh60gv8hgs77nt5atpv4gdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.academinPerformanceCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWKkDn4QoVJpiwl8SKmOf4HwB2j3_uoZg',
    appId: '1:302820889013:ios:9edaad31488e54831649fc',
    messagingSenderId: '302820889013',
    projectId: 'academicperformancecalculator',
    storageBucket: 'academicperformancecalculator.appspot.com',
    iosClientId: '302820889013-bas0k8pdqqh60gv8hgs77nt5atpv4gdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.academinPerformanceCalculator',
  );
}
